### ISSUE TITLE
Extension fails with SyntaxError: redeclaration of let renderer in Gnome Versioon 3.28.1

### ISSUE THREAD

**Issue by shackra** [projecthamster/shell-extension#283] opened 2018-05-03 18:46 UTC
```
SyntaxError: redeclaration of let renderer

Stack trace:
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
```

**Comment by elbenfreund** [comment] 2018-05-04 09:55
Most likely a dupe of #281 et al.
If not please feel free to reopen!

**Closed as completed by elbenfreund** 2018-05-04 09:55 UTC
Labels: bug, duplicate
