### ISSUE TITLE
Does'nt work on archlinux with gnome

### ISSUE THREAD

**Issue by johnparra** [projecthamster/shell-extension#289] opened 2018-07-17 13:12 UTC
SyntaxError: redeclaration of let renderer

```Stack trace:
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43

**Comment by karolszk** [comment] 2018-07-18 21:12
this is plugin error on gnome 3.28 (debian sid/buster) too

**Comment by karolszk** [comment] 2018-07-23 12:17
@johnparra  I've just compiled from the latest git https://github.com/projecthamster/hamster-shell-extension and works perfectly. :) Regards, Karol

**Comment by eigoor** [comment] 2018-08-31 10:55
I had the same error on archlinux. Using the latest version from the develop branch fixed the problem for me.

**Comment by DirkHoffmann** [comment] 2020-03-02 13:30
This issue is quite old. One negative (@johnparra), two positive (@karolszk, @eigoor) feedbacks.
Can we close it or does it need further attention?

**Comment by karolszk** [comment] 2020-03-02 17:26
Hi!, plugin still works fine, on gnome 3.30.2. too, I looked at log and here below is what I found:

mar 01 22:58:20 nvme gnome-shell[2779]: g_object_run_dispose: assertion 'G_IS_OBJECT (object)' failed
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #12   7ffc0ec5b370 b   self-hosted:979 (7f931b4f01f0 @ 440)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #11   7ffc0ec5b2a0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f931b4b0b80 @ 71)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #10   55f787785c50 i   resource:///org/gnome/shell/ui/calendar.js:802 (7f931b2a89d0 @ 22)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #9   7ffc0ec5a320 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f931b4b0b80 @ 71)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #8   55f787785cd0 i   resource:///org/gnome/shell/ui/messageTray.js:481 (7f931b29a310 @ 22)
mar 01 22:58:20 nvme gnome-shell[2779]: Object Gio.Settings (0x55f787ca96b0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #7   7ffc0ec593b0 b   resource:///org/gnome/gjs/modules/signals.js:128 (7f931b4c18b0 @ 386)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #6   55f787785d58 i   resource:///org/gnome/shell/ui/windowAttentionHandler.js:44 (7f931ae17820 @ 17)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #5   7ffc0ec58410 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f931b4b0b80 @ 71)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #4   55f787785dd0 i   resource:///org/gnome/shell/ui/windowAttentionHandler.js:100 (7f931ae17d30 @ 42)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #3   7ffc0ec574a0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f931b4b0b80 @ 71)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #2   55f787785e70 i   resource:///org/gnome/shell/ui/messageTray.js:814 (7f931b29d8b0 @ 28)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #1   7ffc0ec56500 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f931b4b0b80 @ 71)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #0   55f787785f10 i   resource:///org/gnome/shell/ui/messageTray.js:236 (7f931b298790 @ 42)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: == Stack trace for context 0x55f7854c21b0 ==
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #12   7ffc0ec5b370 b   self-hosted:979 (7f931b4f01f0 @ 440)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #11   7ffc0ec5b2a0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f931b4b0b80 @ 71)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #10   55f787785c50 i   resource:///org/gnome/shell/ui/calendar.js:802 (7f931b2a89d0 @ 22)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #9   7ffc0ec5a320 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f931b4b0b80 @ 71)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #8   55f787785cd0 i   resource:///org/gnome/shell/ui/messageTray.js:481 (7f931b29a310 @ 22)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #7   7ffc0ec593b0 b   resource:///org/gnome/gjs/modules/signals.js:128 (7f931b4c18b0 @ 386)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #6   55f787785d58 i   resource:///org/gnome/shell/ui/windowAttentionHandler.js:44 (7f931ae17820 @ 17)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #5   7ffc0ec58410 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f931b4b0b80 @ 71)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #4   55f787785dd0 i   resource:///org/gnome/shell/ui/windowAttentionHandler.js:100 (7f931ae17d30 @ 42)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #3   7ffc0ec574a0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f931b4b0b80 @ 71)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #2   55f787785e70 i   resource:///org/gnome/shell/ui/messageTray.js:814 (7f931b29d8b0 @ 28)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #1   7ffc0ec56500 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f931b4b0b80 @ 71)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: #0   55f787785f10 i   resource:///org/gnome/shell/ui/messageTray.js:235 (7f931b298790 @ 22)
mar 01 22:58:20 nvme org.gnome.Shell.desktop[2779]: == Stack trace for context 0x55f7854c21b0 ==
mar 01 22:58:20 nvme gnome-shell[2779]: g_object_run_dispose: assertion 'G_IS_OBJECT (object)' failed

**Comment by mwilck** [comment] 2020-04-30 22:00
@karolszk, I see no indication in your log that the hamster extension is faulty.

@DirkHoffmann, perhaps we should set a target date at which we close this, unless evidence is provided that this problem persists.

**Comment by karolszk** [comment] 2020-05-01 16:52
Hi @mwilck ok, so probably this is  gnome-shell errors.

**Comment by DirkHoffmann** [comment] 2020-05-02 10:49
> @DirkHoffmann, perhaps we should set a target date at which we close this, unless evidence is provided that this problem persists.

You are right. In this case I will even go faster, as there are many implicit deadlines passed.
Issue reported 2018 – one negative, two positive feedbacks, no activity for 2 years – catchup March 2nd, one feedback, no evidence for a persisting bug for 2 months – and your reminder, @mwilck. (Thank you!) 
There is no point keeping it open.

**Closed as completed by DirkHoffmann** 2020-05-02 10:49 UTC
Labels: bug, waiting for feedback
