### ISSUE TITLE
this.panelWidget is null when disabling extension

### ISSUE THREAD

**Issue by matthijskooijman** [projecthamster/shell-extension#359] opened 2023-05-31 07:18 UTC
I'm on Gnome 44 on Fedora 38 running `develop` branch latest version (commit 75541ac2) and got this error in `journalctl -xe` when trying to disable the extension by toggling the slider in Extensions app:

```
May 31 08:52:56 uberneek gnome-shell[294737]: Shutting down hamster-shell-extension.
May 31 08:52:56 uberneek gnome-shell[294737]: Object .Gjs_places-menu_gnome-shell-extensions_gcampax_github_com_extension_PlacesMenu (0x564c9555a770), has been already disposed >
May 31 08:52:56 uberneek gnome-shell[294737]: == Stack trace for context 0x564c943ecc60 ==
May 31 08:52:56 uberneek gnome-shell[294737]: #0   564c9b3b1f58 i   /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com/extension.js:160 (a1b>
May 31 08:52:56 uberneek gnome-shell[294737]: #1   7fff10688f10 b   resource:///org/gnome/shell/ui/extensionSystem.js:125 (2af59ea13970 @ 407)
May 31 08:52:56 uberneek gnome-shell[294737]: #2   564c9b3b1dc8 i   resource:///org/gnome/shell/ui/extensionSystem.js:565 (2af59ea17150 @ 456)
May 31 08:52:56 uberneek gnome-shell[294737]: #3   564c9b3b1d48 i   resource:///org/gnome/shell/ui/extensionSystem.js:627 (2af59ea173d0 @ 12)
May 31 08:52:56 uberneek gnome-shell[294737]: #4   7fff1068ac90 b   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730 (389b78cc90 @ 169)
May 31 08:52:56 uberneek gnome-shell[294737]: #5   564c9b3b1ca0 i   resource:///org/gnome/shell/ui/extensionSystem.js:238 (2af59ea13ab0 @ 198)
May 31 08:52:56 uberneek gnome-shell[294737]: #6   564c9b3b1c18 i   resource:///org/gnome/shell/ui/shellDBus.js:451 (16d23ed68830 @ 20)
May 31 08:52:56 uberneek gnome-shell[294737]: #7   564c9b3b1b38 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329 (389b785f10 @ 185)
May 31 08:52:56 uberneek gnome-shell[294737]: #8   564c9b3b1a88 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408 (389b78c0b0 @ 34)
May 31 08:52:56 uberneek gnome-shell[294737]: Window manager warning: Trying to remove non-existent keybinding "show-hamster-dropdown".
May 31 08:52:56 uberneek gnome-shell[294737]: Shutting down hamster-shell-extension.
May 31 08:52:56 uberneek gnome-shell[294737]: JS ERROR: Extension contact@projecthamster.org: TypeError: this.panelWidget is null
                                              _removeWidget@/home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/extension.js:283:13
                                              disable@/home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/extension.js:195:14
                                              _callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:125:49
                                              _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:565:24
                                              _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:627:18
                                              createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
                                              disableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:238:29
                                              DisableExtension@resource:///org/gnome/shell/ui/shellDBus.js:451:38
                                              _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
                                              _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
```

The 'places menu' bit might be irrelevant, but that `this.panelWidget is null` looks like a Hamster Indicator issue.  Should I leave this report here, or raise a new Issue?

_Originally posted by @neekfenwick in https://github.com/projecthamster/hamster-shell-extension/issues/327#issuecomment-1569382078_

**Comment by matthijskooijman** [comment] 2023-05-31 07:25
I have also observed this symptom when working on #358, but I think that was then because hamster DBUS disappearing would try to disable the extension twice, leading to this error. In the current develop branch, this disable-on-DBUS-disappear is no longer done, so that cannot explain this problem.

But based on my earlier analysis of this error message, I suspect that the `disable()` method is now also called twice for some reason, or it is called before the extension is properly initialized (i.e. before `panelWidget` is set), maybe because the DBUS connection failed?

Maybe you could add some debug output to check what is happening exactly? You can use the `console.log` function for that, see e.g. https://github.com/projecthamster/hamster-shell-extension/blob/75541ac253e2222f0a0b6458b54710a00fb67a5a/extension/extension.js#L227

**Comment by mwilck** [comment] 2023-05-31 07:30
I have GNOME 44.1 here, same version of the hamster extension, and I don't this issue. Could you add some global.log messages in the disable() method in extension.js and see where the value of this.panelwidget changes to null?

**Comment by neekfenwick** [comment] 2023-05-31 14:58
Thanks guys. Not much to add here I'm afraid. *Edit* I think I got the wrong line 283 before, the line numbers shifted when I added the log lines.

I've added `global.log` calls both in `disable()` and `_removeWidget()` - I see from the line number 283 in my original stack trace posted above the error seems to be in `_removeWidget`, I guess when `placement` is not 1 or 2 and it tries to do:

`Main.panel._rightBox.remove_actor(this.panelWidget.container);`

I'm very unfamiliar with Gnome extension code, and the error is not reproducible at present, but I've disabled a lot of other extensions to try to fix a shell crash when pressing Super key for the Overview screen.  With others disabled, `journalctl -xe` shows a clean operation, toggling the extension off shows `disable` only called once, first and last lines are my debug:

```
May 31 21:51:26 uberneek gnome-shell[30308]: DEBUG: disable called.
May 31 21:51:26 uberneek gnome-shell[30308]: Shutting down hamster-shell-extension.
May 31 21:51:26 uberneek gnome-shell[30308]: _removeWidget called with placement (0), this.panelWidget ([0x55d2d815aa30 Gjs_widgets_panelWidget_PanelWidget.panel-button panel-status-button:first-child last-child ("No activity")])
```
I will keep an eye on this tomorrow and try to report more info.

**Comment by neekfenwick** [comment] 2023-06-12 13:09
I've not had that same error again, but I did just get a slightly different one, around the time that Gnome Shell crashed.  I think it's related to the discussion at https://gitlab.gnome.org/GNOME/mutter/-/issues/2700 and is probably not a Hamster problem at all, or may be something that hasn't been guarded against because it's so unexpected.

This time, the shell crashed when I hit the Super key to go to the Overview (as in the gitlabl issue above), the shell restarted, then I got a popup message with the same error message as I saw in the journal when checking `journalctl -xe`:
```
Jun 12 19:55:54 uberneek gnome-shell[183022]: error: Hamster: Failed to get activities: TypeError: layout is null
```

This was in the middle of lots of error logging relating to the shell crash:
```
Jun 12 19:55:33 uberneek gnome-shell[3404]: **
Jun 12 19:55:33 uberneek gnome-shell[3404]: Clutter:ERROR:../clutter/clutter/clutter-stage.c:3961:clutter_stage_notify_grab_on_pointer_entry: assertion failed: (!implicit_grab_cancelled)
Jun 12 19:55:33 uberneek audit[3404]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3404 comm="gnome-shell" exe="/usr/bin/gnome-she>
Jun 12 19:55:33 uberneek audit: BPF prog-id=94 op=LOAD
Jun 12 19:55:33 uberneek gnome-shell[3404]: Bail out! Clutter:ERROR:../clutter/clutter/clutter-stage.c:3961:clutter_stage_notify_grab_on_pointer_entry: assertion failed: (!implicit_grab_cancell>
Jun 12 19:55:33 uberneek gnome-shell[3404]: == Stack trace for context 0x55d43d6ae640 ==
Jun 12 19:55:33 uberneek gnome-shell[3404]: #0   55d444b36940 i   resource:///org/gnome/shell/ui/main.js:596 (7b6088babf0 @ 108)
Jun 12 19:55:33 uberneek gnome-shell[3404]: #1   55d444b36890 i   resource:///org/gnome/shell/ui/overview.js:508 (c5c630825b0 @ 220)
Jun 12 19:55:33 uberneek gnome-shell[3404]: #2   55d444b367f0 i   resource:///org/gnome/shell/ui/overview.js:544 (c5c63082600 @ 182)
Jun 12 19:55:33 uberneek gnome-shell[3404]: #3   55d444b36750 i   resource:///org/gnome/shell/ui/overview.js:658 (c5c63082880 @ 87)
Jun 12 19:55:33 uberneek gnome-shell[3404]: #4   55d444b36698 i   resource:///org/gnome/shell/ui/overviewControls.js:451 (c5c630853d0 @ 381)
Jun 12 19:55:33 uberneek audit: BPF prog-id=95 op=LOAD
Jun 12 19:55:33 uberneek systemd[1]: Created slice system-systemd\x2dcoredump.slice - Slice /system/systemd-coredump.
[... cut lots of stack traces similar to at the gitlab issue referenced above ...]
Jun 12 19:55:36 uberneek systemd[2719]: Started org.gnome.Shell@x11.service - GNOME Shell on X11.
[... cut a little more stuff ...]
Jun 12 19:55:38 uberneek gnome-shell[183022]: GNOME Shell started at Mon Jun 12 2023 19:55:35 GMT+0700 (Indochina Time)
Jun 12 19:55:38 uberneek gnome-shell[183022]: Registering session with GDM
Jun 12 19:55:38 uberneek gnome-shell[183022]: Object St.Icon (0x55cbbfcb6690), has been already disposed — impossible to set any property on it. This might be caused by the object having been d>
Jun 12 19:55:38 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:38 uberneek gnome-shell[183022]: #0   7ffceff894e0 b   /home/neek/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:743 (910e406f880 @ 322)
Jun 12 19:55:38 uberneek gnome-shell[183022]: #1   7ffceff89580 b   self-hosted:632 (910e401a510 @ 15)
Jun 12 19:55:38 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:38 uberneek gnome-shell[183022]: #0   7ffceff894e0 b   /home/neek/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:743 (910e406f880 @ 322)
Jun 12 19:55:38 uberneek gnome-shell[183022]: #1   7ffceff89580 b   self-hosted:632 (910e401a510 @ 15)
Jun 12 19:55:38 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:38 uberneek gnome-shell[183022]: #0   7ffceff894e0 b   /home/neek/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:743 (910e406f880 @ 322)
Jun 12 19:55:38 uberneek gnome-shell[183022]: #1   7ffceff89580 b   self-hosted:632 (910e401a510 @ 15)
Jun 12 19:55:38 uberneek gnome-shell[183022]: Object St.Icon (0x55cbbfcbef50), has been already disposed — impossible to set any property on it. This might be caused by the object having been d>
Jun 12 19:55:38 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:38 uberneek gnome-shell[183022]: #0   7ffceff894e0 b   /home/neek/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:743 (910e406f880 @ 322)
Jun 12 19:55:38 uberneek gnome-shell[183022]: #1   7ffceff89580 b   self-hosted:632 (910e401a510 @ 15)
Jun 12 19:55:38 uberneek gnome-shell[183022]: Object St.Icon (0x55cbbfcc4ee0), has been already disposed — impossible to set any property on it. This might be caused by the object having been d>
Jun 12 19:55:38 uberneek gnome-shell[183022]: Object St.Icon (0x55cbbfccae50), has been already disposed — impossible to set any property on it. This might be caused by the object having been d>
Jun 12 19:55:40 uberneek systemd[2719]: Started dbus-:1.2-org.gnome.Contacts.SearchProvider@1.service.
Jun 12 19:55:40 uberneek systemd[2719]: Started dbus-:1.2-org.gnome.Nautilus@2.service.
Jun 12 19:55:40 uberneek systemd[2719]: Started dbus-:1.2-org.gnome.Settings.SearchProvider@1.service.
Jun 12 19:55:40 uberneek systemd[2719]: Starting gnome-terminal-server.service - GNOME Terminal Server...
Jun 12 19:55:40 uberneek nautilus[183502]: Connecting to org.freedesktop.Tracker3.Miner.Files
Jun 12 19:55:40 uberneek systemd[2719]: Started gnome-terminal-server.service - GNOME Terminal Server.
Jun 12 19:55:40 uberneek systemd[2719]: Started dbus-:1.2-org.gnome.DiskUtility@2.service.
Jun 12 19:55:41 uberneek systemd[2719]: Started dbus-:1.2-org.gnome.Hamster.GUI@0.service.
[... cut more successful startup ...]
Jun 12 19:55:50 uberneek gnome-shell[183022]: loading user theme: /home/neek/.themes/Minwaita/gnome-shell/gnome-shell.css
Jun 12 19:55:54 uberneek gnome-shell[183022]: Object St.Label (0x55cbbaf526b0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed fro>
Jun 12 19:55:54 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:54 uberneek gnome-shell[183022]: #0   55cbbfc63ca0 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:247 (910e40987e0 @ 100)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #1   55cbbfc63bd8 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:189 (910e40986a0 @ 330)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #2   7ffceff88f40 b   self-hosted:1121 (35b36ae73f60 @ 501)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #3   55cbbfc63b28 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115 (35b36ae855b0 @ 277)
Jun 12 19:55:54 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:54 uberneek gnome-shell[183022]: #0   55cbbfc63ca0 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:248 (910e40987e0 @ 120)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #1   55cbbfc63bd8 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:189 (910e40986a0 @ 330)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #2   7ffceff88f40 b   self-hosted:1121 (35b36ae73f60 @ 501)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #3   55cbbfc63b28 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115 (35b36ae855b0 @ 277)
Jun 12 19:55:54 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:54 uberneek gnome-shell[183022]: #0   55cbbfc63ca0 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:249 (910e40987e0 @ 140)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #1   55cbbfc63bd8 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:189 (910e40986a0 @ 330)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #2   7ffceff88f40 b   self-hosted:1121 (35b36ae73f60 @ 501)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #3   55cbbfc63b28 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115 (35b36ae855b0 @ 277)
Jun 12 19:55:54 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:54 uberneek gnome-shell[183022]: #0   55cbbfc63d38 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/todaysFactsWidget.js:194 (910e409ba60 @ 22)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #1   55cbbfc63ca0 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/factsBox.js:93 (910e4098ba0 @ 28)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #2   55cbbfc63bd8 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:190 (910e40986a0 @ 358)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #3   7ffceff88f40 b   self-hosted:1121 (35b36ae73f60 @ 501)
Jun 12 19:55:54 uberneek gnome-shell[183022]: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 12 19:55:54 uberneek gnome-shell[183022]: #4   55cbbfc63b28 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115 (35b36ae855b0 @ 277)
Jun 12 19:55:54 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:54 uberneek gnome-shell[183022]: #0   7ffceff884d0 b   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/todaysFactsWidget.js:180 (910e409b880 @ 41)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #1   55cbbfc63d38 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/todaysFactsWidget.js:195 (910e409ba60 @ 43)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #2   55cbbfc63ca0 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/factsBox.js:93 (910e4098ba0 @ 28)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #3   55cbbfc63bd8 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:190 (910e40986a0 @ 358)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #4   7ffceff88f40 b   self-hosted:1121 (35b36ae73f60 @ 501)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #5   55cbbfc63b28 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115 (35b36ae855b0 @ 277)
Jun 12 19:55:54 uberneek gnome-shell[183022]: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 12 19:55:54 uberneek gnome-shell[183022]: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 12 19:55:54 uberneek gnome-shell[183022]: Object St.Label (0x55cbbaf526b0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed fro>
Jun 12 19:55:54 uberneek gnome-shell[183022]: Object St.Icon (0x55cbbaf54770), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from>
Jun 12 19:55:54 uberneek gnome-shell[183022]: Object St.Widget (0x55cbbade72c0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed fr>
Jun 12 19:55:54 uberneek gnome-shell[183022]: Object St.Widget (0x55cbbade72c0), has been already disposed — impossible to get any property from it. This might be caused by the object having be>
Jun 12 19:55:54 uberneek gnome-shell[183022]: error: Hamster: Failed to get activities: TypeError: layout is null
Jun 12 19:55:54 uberneek gnome-shell[183022]: Object St.Label (0x55cbbaf526b0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed fro>
Jun 12 19:55:54 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:54 uberneek gnome-shell[183022]: #0   55cbbfc63ca0 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:247 (910e40987e0 @ 100)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #1   55cbbfc63bd8 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:189 (910e40986a0 @ 330)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #2   7ffceff88f40 b   self-hosted:1121 (35b36ae73f60 @ 501)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #3   55cbbfc63b28 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:117 (35b36ae855b0 @ 322)
Jun 12 19:55:54 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:54 uberneek gnome-shell[183022]: #0   55cbbfc63ca0 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:248 (910e40987e0 @ 120)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #1   55cbbfc63bd8 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:189 (910e40986a0 @ 330)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #2   7ffceff88f40 b   self-hosted:1121 (35b36ae73f60 @ 501)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #3   55cbbfc63b28 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:117 (35b36ae855b0 @ 322)
Jun 12 19:55:54 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:54 uberneek gnome-shell[183022]: #0   55cbbfc63ca0 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:249 (910e40987e0 @ 140)
Jun 12 19:55:54 uberneek gnome-shell[183022]: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 12 19:55:54 uberneek gnome-shell[183022]: #1   55cbbfc63bd8 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:189 (910e40986a0 @ 330)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #2   7ffceff88f40 b   self-hosted:1121 (35b36ae73f60 @ 501)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #3   55cbbfc63b28 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:117 (35b36ae855b0 @ 322)
Jun 12 19:55:54 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:54 uberneek gnome-shell[183022]: #0   55cbbfc63d38 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/todaysFactsWidget.js:194 (910e409ba60 @ 22)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #1   55cbbfc63ca0 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/factsBox.js:93 (910e4098ba0 @ 28)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #2   55cbbfc63bd8 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:190 (910e40986a0 @ 358)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #3   7ffceff88f40 b   self-hosted:1121 (35b36ae73f60 @ 501)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #4   55cbbfc63b28 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:117 (35b36ae855b0 @ 322)
Jun 12 19:55:54 uberneek gnome-shell[183022]: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 12 19:55:54 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:54 uberneek gnome-shell[183022]: #0   7ffceff884d0 b   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/todaysFactsWidget.js:180 (910e409b880 @ 41)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #1   55cbbfc63d38 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/todaysFactsWidget.js:195 (910e409ba60 @ 43)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #2   55cbbfc63ca0 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/factsBox.js:93 (910e4098ba0 @ 28)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #3   55cbbfc63bd8 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:190 (910e40986a0 @ 358)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #4   7ffceff88f40 b   self-hosted:1121 (35b36ae73f60 @ 501)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #5   55cbbfc63b28 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:117 (35b36ae855b0 @ 322)
Jun 12 19:55:54 uberneek gnome-shell[183022]: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 12 19:55:54 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:54 uberneek gnome-shell[183022]: #0   55cbbfc63de0 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/totalTimeWidget.js:63 (910e409b740 @ 38)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #1   55cbbfc63d38 i   resource:///org/gnome/gjs/modules/script/_legacy.js:83 (35b36ae8f510 @ 69)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #2   55cbbfc63ca0 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/factsBox.js:94 (910e4098ba0 @ 51)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #3   55cbbfc63bd8 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:190 (910e40986a0 @ 358)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #4   7ffceff88f40 b   self-hosted:1121 (35b36ae73f60 @ 501)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #5   55cbbfc63b28 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:117 (35b36ae855b0 @ 322)
Jun 12 19:55:54 uberneek gnome-shell[183022]: Object St.Label (0x55cbbaf526b0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed fro>
Jun 12 19:55:54 uberneek gnome-shell[183022]: == Stack trace for context 0x55cbb7b17090 ==
Jun 12 19:55:54 uberneek gnome-shell[183022]: #0   55cbbfc63d38 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/categoryTotalsWidget.js:66 (910e409b5b0 @ 3>
Jun 12 19:55:54 uberneek gnome-shell[183022]: #1   55cbbfc63ca0 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/factsBox.js:95 (910e4098ba0 @ 74)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #2   55cbbfc63bd8 i   /home/neek/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:190 (910e40986a0 @ 358)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #3   7ffceff88f40 b   self-hosted:1121 (35b36ae73f60 @ 501)
Jun 12 19:55:54 uberneek gnome-shell[183022]: #4   55cbbfc63b28 i   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:117 (35b36ae855b0 @ 322)
Jun 12 19:55:54 uberneek gnome-shell[183022]: Object St.Icon (0x55cbbaf54770), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from>
Jun 12 19:55:54 uberneek gnome-shell[183022]: Object St.Widget (0x55cbbade72c0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed fr>
Jun 12 19:55:54 uberneek gnome-shell[183022]: Object St.Widget (0x55cbbade72c0), has been already disposed — impossible to get any property from it. This might be caused by the object having be>
Jun 12 19:55:54 uberneek gnome-shell[183022]: Object .Gjs_TotalTime (0x55cbbade9fe0), has been already disposed — impossible to access it. This might be caused by the object having been destroy>
Jun 12 19:55:54 uberneek gnome-shell[183022]: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 12 19:55:54 uberneek gnome-shell[183022]: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 12 19:55:54 uberneek gnome-shell[183022]: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 12 19:55:54 uberneek gnome-shell[183022]: Object .Gjs_widgets_categoryTotalsWidget_CategoryTotals (0x55cbbade8570), has been already disposed — impossible to access it. This might be caused>
Jun 12 19:55:54 uberneek gnome-shell[183022]: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 12 19:55:54 uberneek gnome-shell[183022]: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 12 19:55:54 uberneek gnome-shell[183022]: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Jun 12 19:56:20 uberneek systemd[1]: systemd-hostnamed.service: Deactivated successfully.
```

So it looks similar to the original `this.panelWidget is null when disabling extension` but this time it's a different block of code, from the stack trace of `panelWIdget.js:247` it seems to be in `updatePanelDisplay()` where it tries to reference `this.panelLabel.set_text(getLabelString(fact))` but I don't see why it my journal log above says `TypeError: layout is null` .. but, I'm not very experienced at reading these errors.

**Comment by mwilck** [comment] 2023-06-14 07:21
In the middle of the Shell crashing, I suppose anything can happen to a plugin like ours. I wouldn't invest into analyzng this further unless it occurs in a clean environment, too.

**Comment by neekfenwick** [comment] 2023-06-14 08:48
@mwilck yeah, I'm with you... I can't reproduce the shell crash reliably enough to debug anything and don't know the code well enough to easily dig deeper.  @matthijskooijman can you Close this issue please? I don't have privs.

**Closed as completed** 2023-06-14 20:10 UTC
