### ISSUE TITLE
Support for GNOME 45

### ISSUE THREAD

**Issue by mwilck** [projecthamster/shell-extension#362] opened 2023-09-22 21:54 UTC
We need to add [support for GNOME 45](https://gjs.guide/extensions/upgrading/gnome-shell-45.html).

I've pushed pushing my code with GNOME 45 support to the **[362-support-for-gnome-45 branch](https://github.com/projecthamster/hamster-shell-extension/tree/362-support-for-gnome-45)** branch in this repository.

The branch seems to work. I'm using it right now. Please test and please post any issues here.

**Comment by mwilck** [comment] 2023-09-22 21:59
@hedayat for information.

**Comment by hedayat** [comment] 2023-09-22 22:49
Thanks for starting the work. I didn't know about that, but I'll most likely upgrade to latest Fedora Beta tomorrow, which comes with gnome 45. So, I'll try to help as much as I can (might not be much though, at least for a few days).

**Comment by mwilck** [comment] 2023-09-24 21:47
I've just pushed an update.

### Good news

The extension is displayed in the panel, and the pop-up shows and works as far as I've tested.
![Screenshot from 2023-09-24 23-36-39a](https://github.com/projecthamster/hamster-shell-extension/assets/15961354/2f2ad97e-644e-464b-a344-044d1c083723)

The settings can be opened from the GNOME extensions tool and look ok-ish

![image](https://github.com/projecthamster/hamster-shell-extension/assets/15961354/f8971cb1-7470-4ec3-8fc5-93661926fa2e)

### Not-so-good news

The settings aren't applied correctly yet. The "global hotkey" entry doesn't work at all. (Note that I basically had to re-write the preferences dialog from scratch, copying code from the "window-list" standard extension).

**Comment by hedayat** [comment] 2023-09-25 12:11
Thanks a lot. Unfortunately, I've not yet started using Gnome 45, and cannot test the code till tomorrow. But I guess it's completely working till then :sweat_smile:

**Comment by mwilck** [comment] 2023-09-25 16:50
The settings dialog works now, too. It's still necessary to logout and relogin to apply the settings, and one day we should fix that, but it's no different from the current behavior until GNOME 44 and earlier.

I've created #363 in preparation of a GNOME 45 PR. Anyway, even if testing by you and hopefully other people is successful, we need to discuss how to proceed further. GNOME 45 support is exclusive and means that no prior GNOME shell version can be supported. Therefore I suppose the `develop` branch will keep supporting  the older versions for some time to come, and will create a `gnome-shell-45` branch.

**Comment by mwilck** [comment] 2023-09-25 17:13
Re-pushed the branch to 6d31a9b, as I'd made a mistake rebasing it.

**Comment by hedayat** [comment] 2023-09-25 17:20
Thanks a lot! :)

> Therefore I suppose the develop branch will keep supporting the older versions for some time to come, and will create a gnome-shell-45 branch.

I suggest the other way around: create a branch for older versions (e.g. `gjs-version` or `pre-gnome-shell-45`) and let `develop` contain latest code.

**Comment by hedayat** [comment] 2023-09-25 17:24
Well, just so that we have a now almost meaningless `master` branch too. If we want to keep that around, I think it can contain current `develop` branch which is compatible with 44 and below, and then develop branch can contain gnome-shell 45 compatible code until it is considered `release` quality.

**Comment by mwilck** [comment] 2023-09-26 08:55
Right. I thought the original idea was to have `master` in line with e.g.o. But both have bitrotted so much now that it's kind of meaningless. 

If we follow your suggestion, I could actually create a PR against `develop`, which would simplify the review process on GitHub. So yeah, I am in favor of it.

**Comment by mwilck** [comment] 2023-09-26 10:23
There are 2 problems: current `master` is not an ancestor of `develop`, so we can't fast-forward it (the differences are few and mostly related to commit messages, but they aren't zero). Also, IIRC, @elbenfreund has locked the `master` branch, so that nobody except himself can do merges or other updates to the branch (I haven't tried in a long time, though) [^json].

Notifying all members of @projecthamster/gnome-shell-extension here for follow-up discussion.

[^json]: I found that our past team discussions are now only available in an [awkward json format](https://github.com/orgs/projecthamster/teams/gnome-shell-extension/members/archived_team_posts.json), which is very hard to read.

**Comment by hedayat** [comment] 2023-09-26 11:15
Well, maybe its time to create a `main` branch if @elbenfreund is not available. :D

**Comment by matthijskooijman** [comment] 2023-09-26 11:41
I've tried a few times over the past few years to send @elbenfreund e-mail asking for some changes or transferring some rights, but have not received any reply to those. I wonder if it might be worth considering migrating to a new and separate organization to work around such limitations, but that's probably something to discuss elsewhere (maybe organisation-wide, though organisations do not seem to have (public) discussion options).

**Comment by benjaoming** [comment] 2023-09-26 12:37
This is always a huge problem, not to mention that the extension doesn't even have a proper official package on Gnome. I've followed the conversation and all the issues over the years and I could totally get behind a reboot, mainly in terms of governance and distribution. I think renaming the project[1] would help to free up various namespaces in the distribution chain.

[1] for instance to a similar animal that likes running around in wheels, example: "chinchilla"

**Comment by mwilck** [comment] 2023-09-26 13:30
> I wonder if it might be worth considering migrating to a new and separate organization to work around such limitations

I thought the same.

> but that's probably something to discuss elsewhere (maybe organisation-wide, though organisations do not seem to have (public) discussion options).

*This project* doesn't have GitHub discussions, because @elbenfreund would need to enable it, and we're back at square one.[^disc] 

[^disc]: We used to have "team discussions" but GitHub has dropped the feature in favor of the new GitHub discussions, that's where the "awkward json" mentioned above comes from.

I guess we agree that *if* we move to a different organization, we should move the entire project (at least the currently active repos, i.e. "hamster" and "hamster-shell-extension").

About changing the name: I'm unsure if that's a good idea. People will be looking for "hamster", both on e.g.o and elsewhere. AFAICS, nobody owns the name "hamster", and if anyone did, it would probably be @tstriker. IMO we could simply fork the active repos and keep using the name "hamster", as long as we keep true to the spirit of the project (which I think we have done so far).

**Comment by tstriker** [comment] 2023-09-26 14:37
the name 'hamster' ('project hamster', specifically) is not copyrighted and nobody owns it so please keep using it if you want - the name was a reference to the hamster wheel and is a tongue-in-cheek reference to 9-to-5 work.

if elbenfreund has gone missing, you might want to reach out to github support - they might allow transferring the project ownership to a new team. until then you can also just abandon 'master' as github deprecated those in favor to 'main' a while ago anyway.

alternatively, of course, you could make a fork org and leave a message somewhere pointing to it but that might be messier.

Note: i unfortunately don't have extra cycles so i won't be monitoring this nor any other conversations relating to project hamster; i've now set up an auto-filter to keep these out of my inbox. 

Good luck!

**Comment by mwilck** [comment] 2023-09-26 15:58
Thanks a lot, Tom! 

Wrt reaching out to github support, I see that as a last resort. Even if @elbenfreund has turned silent, his contributions are massive and still very valuable, and I wouldn't want to be rude to him. I'd strongly appreciate if he voluntarily assigned someone else (one or more of the currently active people) a maintainer role in this repository though. If he can't or doesn't want to do that, I'd rather move to a fork. That's my personal PoV.

**Comment by matthijskooijman** [comment] 2023-09-27 09:06
To prevent further digressing this issue, I've created https://github.com/projecthamster/hamster/issues/730 for further discussion about regaining access to the repositories and organization.

I suggest moving this issue back to supporting gnome 45, and what branches to use (within the current limitations we have wrt repo access).

**Comment by mwilck** [comment] 2023-09-27 09:20
Thanks, @matthijskooijman. I suppose the general discussion about the future of the project will take some more time.

Meanwhile, once @hedayat has ultimately approved #363, I will create a PR for merging into master (as we'll certainly won't be able to force-push to master, this will require some manual, local merging on my part). Then we'll see if we can merge into master at all. If not, we can still try to create a "main" branch, but we won't be able to change the fact that "develop" is currently the default branch.

**Comment by mwilck** [comment] 2023-09-27 09:22
I pushed another commit to the 362-support-for-gnome-45 branch, fixing an issue that occured when disabling the extension.

**Comment by hedayat** [comment] 2023-10-01 08:15
Well, I finally got to test this, but I need to see if I can fix hamster [python 3.12 compatibility](https://github.com/projecthamster/hamster/issues/731) first...

**Comment by hedayat** [comment] 2023-10-01 08:42
OK, I'm finally able to use the extension under Gnome 45, and so far so good :) At least all functionality I used before are working fine. Thanks!

**Comment by hedayat** [comment] 2023-10-05 14:12
Well, there is one thing. When I select "Add earlier activity", it opens the dialog with the current time selected as the start time, which is an inconvenience sine you almost always want to change it. It's better to remain like previous version: with no start time so that we can write the desired number right away (for me, usually start with time diff; e.g. -120)

**Comment by mwilck** [comment] 2023-10-09 18:02
I haven't changed anything in this respect. The version from the master branch behaves the same.

**Comment by mwilck** [comment] 2023-10-09 18:13
The "add earlier activity" button just executes the equivalent of
```
busctl --user call org.gnome.Hamster.WindowServer \
    /org/gnome/Hamster/WindowServer \
    org.gnome.Hamster.WindowServer \
    edit i 0
```
which also comes up with the current time as start time. So this must be a change in hamster itself, I think.

**Comment by hedayat** [comment] 2023-10-09 18:19
Oh, yeah, thanks! 

So the behavior has changed. Previously, it was either empty, or the current time was selected so that you could type what you wanted right away. I'll try to find-out when it has changed in hamster itself!

**Comment by nmaggioni** [comment] 2023-11-06 18:57
This branch is working fine for me too on GNOME 45, thanks for your efforts.

**Comment by mawe42** [comment] 2023-11-14 08:26
I'm using this branch under GNOME 45 and it's working fine. Thanks a lot for maintaining this extension, I use it every day!

**Comment by yobuntu** [comment] 2023-11-28 08:59
hello, 
thank you for this great  work (for the extension in general and this particular PR).
Is there any chance to see this merged on main soon ? (Gnome 45 is the current gnome version on archlinux, and  it would be great if i could update the aur package with this work)

**Comment by mwilck** [comment] 2023-12-04 15:05
Sorry for the long delay. As discussed previously, I have now created #364.

**Comment by jacek-pliszka** [comment] 2023-12-30 14:44
Fedora 39

OK, it does not fully work for me.

It does not show up on the screen.

Only super-t works.

How to fix it?

**Comment by lefterav** [comment] 2024-01-04 09:28
I am using the GNOME 45 version and I get some errors. Can somebody advise, where to get the logs, so that I submit the respective issues here?

**Comment by jacek-pliszka** [comment] 2024-01-04 09:56
Hi! I am also using GNOME 45 and I had some errors at the beginning but they somehow disappeared later. 
Ensure that your hamster runs correctly without the gnome shell extension first.

**Comment by mwilck** [comment] 2024-01-04 11:34
> I am using the GNOME 45 version and I get some errors. Can somebody advise, where to get the logs, so that I submit the respective issues here?

Can you be a bit more specific? If you "get some errors", you must have seen something going wrong. What? 

Wrt logs, `journalctl -b --user` is your friend.

**Comment by lefterav** [comment] 2024-01-13 17:17
Sure, so every now and then the hamster widget disappears. The message at journal is 

```
Jan 13 15:43:37 nubi gnome-shell[1020865]: Shutting down hamster-shell-extension.
Jan 13 16:20:11 nubi gnome-shell[1020865]: Shutting down hamster-shell-extension.
Jan 13 16:59:35 nubi gnome-shell[1020865]: Shutting down hamster-shell-extension.
Jan 13 17:29:06 nubi gnome-shell[1020865]: Shutting down hamster-shell-extension.
```
Then I went to extension manager, I disabled and re-enabled the hamster extension from the switch. The Extension manager displayed a red dead-end sign and the switch became inactive, displaying the following error:

![image](https://github.com/projecthamster/hamster-shell-extension/assets/339830/72eac60c-362a-43b2-80eb-464bd69b6852)

at the same time, the journal reported the following:

```
Jan 13 18:10:54 nubi gnome-shell[1020865]: Window manager warning: Trying to remove non-existent keybinding "show-hamster-dropdown".
Jan 13 18:10:54 nubi gnome-shell[1020865]: Shutting down hamster-shell-extension.
Jan 13 18:10:54 nubi gnome-shell[1020865]: JS ERROR: Extension contact@projecthamster.org: TypeError: this.panelWidget is null
                                           _removeWidget@file:///home/elav01/.local/share/gnome-shell/extensions/contact@projecthamster.org/extension.js:278:13
                                           disable@file:///home/elav01/.local/share/gnome-shell/extensions/contact@projecthamster.org/extension.js:191:14
```

I haven't found another way to make the widget visible apart from logging out of the gnome session and logging in again.

**Comment by mwilck** [comment] 2024-01-15 12:15
@lefterav: I can't reproduce this. I can disable/enable the extension just fine. This must be caused by the extension being shut down in your environment. Maybe you can shed some light on why this happens?

Anyway I think this should be tracked in a separate issue.

**Comment by jacek-pliszka** [comment] 2024-01-15 12:19
In my case:
1. there were 2 other extensions breaking it
2. I had problems with flatpack version - once I build rpm and installed it  - it worked fine

**Comment by lefterav** [comment] 2024-01-15 14:16
I also just received the following message, but Hamster applet is still running
![image](https://github.com/projecthamster/hamster-shell-extension/assets/339830/ed8efb1b-ac15-4be9-bbb6-a17dcb4e97a8)

**Comment by lefterav** [comment] 2024-01-15 15:31
> @lefterav: I can't reproduce this. I can disable/enable the extension just fine. This must be caused by the extension being shut down in your environment. Maybe you can shed some light on why this happens?
> 
> Anyway I think this should be tracked in a separate issue.

Starting a separate issue

#365

**Comment by hedayat** [comment] 2024-03-30 10:39
OK, I'd say this issue and related PR has been lingering too much, now that [Gnome 46](https://github.com/projecthamster/hamster-shell-extension/issues/366) is also released. And while I guess we didn't expect, it has breaking changes again. So, I guess we should move on, and have a tagging/branching strategy for each time we break compatibility.

**Comment by matthijskooijman** [comment] 2024-03-30 10:56
Didn't we formulate a branching strategy for this already a long time ago?

In any case, merging would still be useful so we have a version that supports gnome 45 and not just gnome 46, but maybe it should be merged to another branch, then.

**Comment by hedayat** [comment] 2024-03-30 11:01
> Didn't we formulate a branching strategy for this already a long time ago?

TBH, I don't remember. If we have, then everything's fine :)

> 
> In any case, merging would still be useful so we have a version that supports gnome 45 and not just gnome 46, but maybe it should be merged to another branch, then.

Yeah, maybe I didn't communicate my intention correctly. I said this issue/PR is lingering too much, I meant that we should merge it ASAP. And as you said that we already have a branching strategy, let's follow it and properly have a merged Gnome 45 support code, and then go with reviewing Gnome 46 PR.

**Closed as completed** 2024-04-03 14:53 UTC
Labels: testing needed

**Comment by hedayat** [comment] 2024-04-03 22:16
@mwilck Sorry, I guess I missed something. Shouldn't we also have a separate tag for gnome shell 45? I doubt the current develop  works on 45 (but I've not tested).

**Comment by andypost** [comment] 2024-04-03 22:46
@hedayat for 45 it needs to patch
```diff
--- metadata.json
+++ metadata.json
@@ -9,9 +9,7 @@
     ],
     "gettext-domain": "hamster-shell-extension",
     "settings-schema": "org.gnome.shell.extensions.project-hamster",
-    "shell-version": [
-        "46"
-    ],
+    "shell-version": ["45", "46"],
     "url": "https://github.com/projecthamster/hamster-shell-extension.git",
     "uuid": "contact@projecthamster.org"
 }
```

**Comment by hedayat** [comment] 2024-04-03 23:43
@andypost And... does it actually work? I intentionally removed 45 from metadata.json, since some APIs were changed and I doubt they also exist in gnome shell 45 (unless gnome 45 provides both old and new APIs).

**Comment by andypost** [comment] 2024-04-04 00:42
I did switch to 46 and it was working

**Comment by hedayat** [comment] 2024-04-04 15:24
Oops, sorry if I wasn't clear enough. I mean, does the latest code, which works on 46, also work on 45 correctly if 45 is added to metadata.json? The new code might not be compatible with gnome shell 45.

**Comment by mwilck** [comment] 2024-04-04 21:17
My bad, I overlooked the fact that you put 46 *instead* of 45 rather than just adding it.

I'll push an update pretending to support both.
Because I had a similar change in another extension, I'm rather confident it will work with both GNOME 45 and 46. But it would be very nice if someone could test that.

**Comment by mwilck** [comment] 2024-04-04 21:20
I just pushed this to the "develop" branch to fix my previous mistake. Please test under GNOME 45. If any issues appear, we'll need to branch once more.

**Comment by hedayat** [comment] 2024-04-04 21:30
Thanks! Hope it works in 45 too.

**Comment by matthijskooijman** [comment] 2024-04-04 21:51
>  Please test under GNOME 45

I'm still on 45, so I tested develop (I was previously running the branch from #364 without problems). Seems to mostly work, but the list of todays activities is displayed empty in the popup:

![image](https://github.com/projecthamster/hamster-shell-extension/assets/194491/2385386b-d561-4e11-ad25-cd1e7cda7071)

In the journal I get these when I open the popup, which I think are related:

```
apr 04 23:28:33 dottie gnome-shell[3036550]: ../clutter/clutter/clutter-actor.c:8802: Actor '<unnamed>[<StScrollBar>:0x5fa74a918780]' tried to allocate a size of 8,00 x -8,00
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StBoxLayout>:0x5fa74a91b960] is on because it needs an allocation. 
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StWidget>:0x5fa74a91c880] is on because it needs an allocation.    
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StLabel>:0x5fa746695b50] is on because it needs an allocation.     
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<ClutterText>:0x5fa748136950] is on because it needs an allocation.
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StLabel>:0x5fa74851f9a0] is on because it needs an allocation.    
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<ClutterText>:0x5fa74aa9f590] is on because it needs an allocation.
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StLabel>:0x5fa74603d990] is on because it needs an allocation.    
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<ClutterText>:0x5fa7485ced50] is on because it needs an allocation.
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StButton>:0x5fa7471e9ad0] is on because it needs an allocation.   
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StIcon>:0x5fa749c6f9f0] is on because it needs an allocation.      
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<ClutterActor>:0x5fa745893850] is on because it needs an allocation.
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StLabel>:0x5fa74ac94300] is on because it needs an allocation.     
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<ClutterText>:0x5fa74baa0b10] is on because it needs an allocation. 
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StLabel>:0x5fa745760f10] is on because it needs an allocation.     
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<ClutterText>:0x5fa7453d6660] is on because it needs an allocation.
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StLabel>:0x5fa747a378e0] is on because it needs an allocation.    
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<ClutterText>:0x5fa748070750] is on because it needs an allocation.
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StButton>:0x5fa74aad03d0] is on because it needs an allocation.   
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StIcon>:0x5fa746091cd0] is on because it needs an allocation.     
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<ClutterActor>:0x5fa746af3ee0] is on because it needs an allocation.
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StButton>:0x5fa747e06360] is on because it needs an allocation.    
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StIcon>:0x5fa74aaa1df0] is on because it needs an allocation.      
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<ClutterActor>:0x5fa74561fb80] is on because it needs an allocation.
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StLabel>:0x5fa748a880b0] is on because it needs an allocation.     
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<ClutterText>:0x5fa748063400] is on because it needs an allocation. 
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StLabel>:0x5fa7481489b0] is on because it needs an allocation.    
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<ClutterText>:0x5fa74548c680] is on because it needs an allocation.
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<StLabel>:0x5fa74804eae0] is on because it needs an allocation.    
apr 04 23:28:33 dottie gnome-shell[3036550]: Can't update stage views actor <unnamed>[<ClutterText>:0x5fa74593ace0] is on because it needs an allocation.
```

I looked around the mutter 45.0 source code a bit and it seems like `add` and `add_child` are pretty much equivalent really (`add` is defined on in `clutter-container.c`, but pretty much only calls `add_child` defined in `clutter-actor.c`), but maybe I'm looking at entirely the wrong code...

I might see if I can pinpoint what line in the 46-fix breaks this, but I probably won't have time now to get to the bottom of this...

**Comment by mwilck** [comment] 2024-04-04 21:56
Too bad...

@hedayat, to my understanding the replacement of `.add_actor()` by `.add_child()` should be well backward compatible. But you also replaced some `.add()` instances by `.add_child()`. Did you find this necessary? @matthijskooijman, can you try reverting just the `.add()` hunks and see if that fixes the issue?

**Comment by hedayat** [comment] 2024-04-04 22:01
> Too bad...
> 
> @hedayat, to my understanding the replacement of `.add_actor()` by `.add_child()` should be well backward compatible. But you also replaced some `.add()` instances by `.add_child()`. Did you find this necessary? @matthijskooijman, can you try reverting just the `.add()` hunks and see if that fixes the issue?

Yes, I actually tried to run the extension, received errors and tried to fix errors. I don't think any of the changes can be reverted. But, replacing `add()` with `add_child()` was just a guess, so there might be another replacement which is compatible with both 45 & 46. But, IIRC, `add()` certainly doesn't work under 46.

**Comment by matthijskooijman** [comment] 2024-04-04 22:34
> But, replacing add() with add_child() was just a guess

It seems to be correct to me, assuming that I've found the right C code here: https://gitlab.gnome.org/GNOME/mutter/-/blob/45.5/clutter/clutter/clutter-container.c?ref_type=tags#L301

> But, IIRC, add() certainly doesn't work under 46.
That entire file was removed in gnome 46.0, so that would make sense.

If I apply this patch, it works again on gnome 45:

```diff
--- a/extension/widgets/todaysFactsWidget.js
+++ b/extension/widgets/todaysFactsWidget.js
@@ -48,7 +48,7 @@ class TodaysFactsWidget extends St.ScrollView {
             reactive: true
         });
         this.factsBox.add_child(this.facts_widget);
-        this.add_child(this.factsBox);
+        this.add_actor(this.factsBox);
 
     }
```

Look at the code for gnome 45.2 (which I am running), it seems that `add_actor` just calls `add_child` here: https://gitlab.gnome.org/GNOME/mutter/-/blob/45.2/clutter/clutter/clutter-container.c?ref_type=tags#L220 through an indirect add call but that *should* always be pointing `container_real_add` which calls `clutter_actor_add_child` here: https://gitlab.gnome.org/GNOME/mutter/-/blob/45.2/clutter/clutter/clutter-container.c?ref_type=tags#L106

One thing that *is* different, is that `add_actor` also calls `clutter_container_create_child_meta` beforehand: https://gitlab.gnome.org/GNOME/mutter/-/blob/45.2/clutter/clutter/clutter-container.c?ref_type=tags#L205, but `clutter_actor_add_child` essentially does the same (it calls the internal version here: https://gitlab.gnome.org/GNOME/mutter/-/blob/45.2/clutter/clutter/clutter-actor.c#L11221 with flags that include ADD_CHILD_CREATE_META which causes `clutter_container_create_child_meta` to be called here as well: https://gitlab.gnome.org/GNOME/mutter/-/blob/45.2/clutter/clutter/clutter-actor.c#L11099 The only difference I can see is that `g_object_freeze_notify` is called before that, maybe that messes things up by delaying allocations or something?

**Comment by matthijskooijman** [comment] 2024-04-04 23:12
I tried simplifying things (e.g. removing all facts and just putting a label there) and making the BoxLayout more similar to the one in factsBox.js, but even then I could not make it work with `add_child`. It seems a bit like using a ScrollView like we do is not compatible with `add_child` somehow? Here's the diff I ended up with, still renders incorrectly in the same way:

```diff
--- a/extension/widgets/todaysFactsWidget.js
+++ b/extension/widgets/todaysFactsWidget.js
@@ -40,16 +40,12 @@ class TodaysFactsWidget extends St.ScrollView {
         this._panelWidget = panelWidget;
 
 
-        this.factsBox = new St.BoxLayout({});
+        this.factsBox = new St.BoxLayout({style_class: 'hamster_box'});
         this.factsBox.set_vertical(true);
-        this.facts_widget = new St.Widget({
-            style_class: 'hamster-activities',
-            layout_manager: new Clutter.GridLayout(),
-            reactive: true
-        });
-        this.factsBox.add_child(this.facts_widget);
-        this.add_child(this.factsBox);
-
+        let fact_list_label = new St.Label({style_class: 'hamster-box-label'});
+        fact_list_label.set_text(_("XXX"));
+        this.factsBox.add_child(fact_list_label);
+        this.actor.add_child(this.factsBox);
     }
 
     /**
@@ -187,8 +183,8 @@ class TodaysFactsWidget extends St.ScrollView {
      * Clear the widget and populate it anew.
      */
     refresh(facts, ongoingFact) {
-        this.facts_widget.remove_all_children();
-        this.populateFactsWidget(facts, ongoingFact);
+        //this.facts_widget.remove_all_children();
+        //this.populateFactsWidget(facts, ongoingFact);
     }
 });
 ```

**Comment by matthijskooijman** [comment] 2024-04-04 23:24
Hm, my last diff above was not so useful: If I try that with `add_actor` instead of `add_child`, it still does not work, so I guess putting labels directly in a ScrollView (I also tried that after the above diff) or in a BoxLayout is not the way to go. I'm just guessing here, though...

**Comment by mwilck** [comment] 2024-04-05 11:13
@matthijskooijman , can you try this?

```diff
diff --git a/extension/widgets/todaysFactsWidget.js b/extension/widgets/todaysFactsWidget.js
index 1734cde..85f1653 100644
--- a/extension/widgets/todaysFactsWidget.js
+++ b/extension/widgets/todaysFactsWidget.js
@@ -47,7 +47,7 @@ class TodaysFactsWidget extends St.ScrollView {
             layout_manager: new Clutter.GridLayout(),
             reactive: true
         });
-        this.factsBox.add_child(this.facts_widget);
+        this.factsBox.actor.add_child(this.facts_widget);
         this.add_child(this.factsBox);
 
     }
```

**Comment by matthijskooijman** [comment] 2024-04-05 11:17
I can try, but I'm not very hopeful. I tried `this.actor.add_child()` yesterday, which got me:

```
apr 05 01:07:03 dottie gnome-shell[3453979]: Usage of object.actor is deprecated for TodaysFactsWidget
                                             get@resource:///org/gnome/shell/ui/environment.js:320:23
                                             _init@file:///home/matthijs/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/todaysFactsWidget.js:56:9
                                             TodaysFactsWidget@file:///home/matthijs/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/todaysFactsWidget.js:36:1
                                             _init@file:///home/matthijs/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/factsBox.js:70:34
                                             PopupBaseMenuItem@resource:///org/gnome/shell/ui/popupMenu.js:80:4
                                             FactsBox@file:///home/matthijs/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/factsBox.js:43:1
                                             _init@file:///home/matthijs/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:99:25
                                             ButtonBox@resource:///org/gnome/shell/ui/panelMenu.js:13:1
                                             PanelMenuButton@resource:///org/gnome/shell/ui/panelMenu.js:99:4
                                             PanelWidget@file:///home/matthijs/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:56:1
                                             deferred_enable@file:///home/matthijs/.local/share/gnome-shell/extensions/contact@projecthamster.org/extension.js:140:28
                                             enable/<@file:///home/matthijs/.local/share/gnome-shell/extensions/contact@projecthamster.org/extension.js:129:14
                                             wrapper/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:251:36
                                             @resource:///org/gnome/shell/ui/init.js:21:20
```

So I suspect that using `.actor` in general is no longer needed, but maybe that deprecation does not apply to the factsbox.

**Comment by matthijskooijman** [comment] 2024-04-05 11:30
Tried it, did not help unfortunately (ongoing facts box still empty).

And also a deprecation working:

    apr 05 13:29:10 dottie gnome-shell[732106]: Usage of object.actor is deprecated for St_BoxLayout

**Comment by mwilck** [comment] 2024-04-05 13:50
It works under GNOME 45 with this admittedly clumsy workaround:

```diff
diff --git a/extension/widgets/todaysFactsWidget.js b/extension/widgets/todaysFactsWidget.js
index 1734cde..29b9bbd 100644
--- a/extension/widgets/todaysFactsWidget.js
+++ b/extension/widgets/todaysFactsWidget.js
@@ -28,6 +28,7 @@ import GObject from 'gi://GObject';
 
 import { gettext as _ } from 'resource:///org/gnome/shell/extensions/extension.js';
 import * as Stuff from '../stuff.js';
+import * as Config from 'resource:///org/gnome/shell/misc/config.js';
 
 /**
  * A widget that lists all facts for *today*.
@@ -48,7 +49,10 @@ class TodaysFactsWidget extends St.ScrollView {
             reactive: true
         });
         this.factsBox.add_child(this.facts_widget);
-        this.add_child(this.factsBox);
+        if (Config.PACKAGE_VERSION.substring(0, 2) == "45")
+            this.add_actor(this.factsBox);
+        else
+            this.add_child(this.factsBox);
 
     }

```

I'll test this under 46 too, and push this until we find a more elegant solution.

**Comment by matthijskooijman** [comment] 2024-04-05 14:01
> It works under GNOME 45 with this admittedly clumsy workaround:

I do not think this warrants investing more time, clumsy workaround seems fine to me (maybe with add a link to this comment thread). I've applied your patch, seems to work as expected now.

**Comment by mwilck** [comment] 2024-04-05 14:01
It might actually be a bug in GNOME shell. I think I'll open an issue there.

**Comment by mwilck** [comment] 2024-04-05 14:02
OTOH, they probably won't care. If they did, they wouldn't be doing this kind of thing to extension maintainers all the time.

**Comment by matthijskooijman** [comment] 2024-04-05 14:07
Yeah, I would not bother, especially if the issue is not present in 46, then it might be a bug that they already fixed.

**Comment by mwilck** [comment] 2024-04-05 14:11
There *is* a simpler solution. We can just continue using `add_actor()` for `St.ScrollView` in GNOME 46. I expect this to break in GNOME 47, but for now, it works.

**Comment by mwilck** [comment] 2024-04-05 14:18
I've pushed a trivial one-line revert to `develop` now that uses `ScrollView.add_actor()`. @matthijskooijman please verify it under GNOME 45 if you have time (I need to do another btrfs snapshot rollback to test it, which is very time consuming).

**Comment by matthijskooijman** [comment] 2024-04-05 14:25
> I've pushed a trivial one-line revert to develop now that uses ScrollView.add_actor(). @matthijskooijman please verify it under GNOME 45 if you have time (I need to do another btrfs snapshot rollback to test it, which is very time consuming).

Heh, and I thought having to log out and in was a lot of work to test this every time ;-p (btw, the nested gnome-shell trick documented in the README for quick testing without relogging seems to have broken at some point - gnome-shell starts up but cannot find hamster, which I guess makes sense since the nested instance has its own dbus bus...).

Anyway, I'm now running develop, seems to work as expected.

**Comment by mwilck** [comment] 2024-04-05 14:37
I've created https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/issues/502 to make the GNOME devs aware of this.

**Comment by mwilck** [comment] 2024-04-05 14:39
> Heh, and I thought having to log out and in was a lot of work to test this every time 

snapshot rollback is neccessary to go back from GNOME 46 to 45. Otherwise I just type Alt-F2 and "r" (yes, still on X11).

**Comment by mwilck** [comment] 2024-04-05 14:42
Lesson learned: I waited 1/2y before pushing the GNOME 45 update (which was large) to `develop`, but for the apparently "simple" GNOME 46 update, I decided to move forward quickly, which played out badly for GNOME 45. Next time I'll be more careful.

**Comment by mwilck** [comment] 2024-04-05 14:45
I've been told I should have opened the GNOME issue against gjs-guide. Here it is: https://gitlab.gnome.org/ewlsh/gjs-guide/-/issues/91

**Comment by hedayat** [comment] 2024-04-05 21:02
> the nested gnome-shell trick documented in the README for quick testing without relogging seems to have broken at some point -

Interesting... it still works for me. :thinking:

**Comment by hedayat** [comment] 2024-04-07 11:03
> I've pushed a trivial one-line revert to `develop` now that uses `ScrollView.add_actor()`. @matthijskooijman please verify it under GNOME 45 if you have time (I need to do another btrfs snapshot rollback to test it, which is very time consuming).

Well, Gnome 46 compatibility is broken now: https://github.com/projecthamster/hamster-shell-extension/pull/368#issuecomment-2041428358

~~I think let's just accept to have a separate branch for 45!~~ Well, its certainly a possibility, but since this is just one line, we might do something to have a shared branch also. :P Anyway, whatever works is good!
